RentReview/RentReview/Controllers/InventoryController.cs
namespace RentReview.Controllers
{
    using Microsoft.AspNet.Identity;
    using RentReview.CustomFilters;
    using RentReview.Models;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Web.Mvc;

    [Authorize]
    public class InventoryController : BaseController
    {
        // GET: RentItems
        public ActionResult Index(string UserId)
        {
            switch (this.VerifyOwnership(UserId))
            {
                case UserStatus.Current:
                    UserId = this.CurrentUserIdentity.GetUserId();
                    break;
                case UserStatus.Stranger:
                    ViewBag.Username = this.Db.Profiles.Where(profile => profile.UserId == UserId).FirstOrDefault().Name;
                    break;
                case UserStatus.Undefined:
                    return new HttpNotFoundResult("Invalid User");
            }

            if (Request.IsAjaxRequest())
            {
                IEnumerable<KeyValuePair<int, string>> ownedItems = this.Db.Inventory.Where(item => item.Owner.UserId == UserId && !item.Deleted)
                                                                                     .ToList()
                                                                                     .Select( item => new KeyValuePair<int, string>(item.Id, item.Name));
                return Json(ownedItems, JsonRequestBehavior.AllowGet);
            }
            else
            {
                IEnumerable<RentItem> ownedItems = this.Db.Inventory.Where(item => item.Owner.UserId == UserId && !item.Deleted);
                return View(ownedItems);
            }            
        }

        // GET: RentItems/Create
        [ProfileVerification]
        public ActionResult Create()
        {
            return View();
        }

        // POST: RentItems/Create
        [HttpPost]
        [ProfileVerification]
        public ActionResult Create(RentItem item)
        {
            try
            {
                if (ModelState.IsValid && item != null)
                {
                    item.Owner = this.GetCurrentUserProfile();
                    this.Db.Inventory.Add(item);
                    this.Db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: RentItems/Edit/5
        [HttpGet]
        [ProfileVerification]
        public ActionResult Edit(int id)
        {
            RentItem item = this.Db.Inventory.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            return View(item);
        }

        // POST: RentItems/Edit/5
        [HttpPost]
        [ProfileVerification]
        public ActionResult SaveEdit(RentItem item)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    this.Db.Entry(item).State = EntityState.Modified;
                    this.Db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: RentItems/Delete/5
        [HttpGet]
        [ProfileVerification]
        public ActionResult Delete(int id)
        {
            RentItem item = this.Db.Inventory.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            return View(item);
        }

        // POST: RentItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ProfileVerification]
        public ActionResult SaveDelete(int id)
        {
            try
            {
                RentItem item = this.Db.Inventory.Find(id);

                if (item == null)
                {
                    return HttpNotFound("The item you are trying to delete doesn't exist!");
                }

                item.Deleted = true;

                this.Db.Entry(item).State = EntityState.Modified;
                this.Db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult GetItemCount(string UserId = null)
        {
            if (string.IsNullOrEmpty(UserId))
            {
                return new HttpNotFoundResult();
            }
            
            int ownedItemCount = this.Db.Inventory.Where(item => item.Owner.UserId == UserId && !item.Deleted).Count();
            return (Content($"Inventory contains {ownedItemCount} item(s)."));
        }
    }
}

RentReview/RentReview/Controllers/ReviewController.cs
namespace RentReview.Controllers
{
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Linq;
    using System.Web.Mvc;
    using Microsoft.AspNet.Identity;
    using RentReview.CustomFilters;
    using RentReview.Models;

    public class ReviewController : BaseController
    {
        // GET: Review
        public ActionResult Index(string UserId)
        {
            switch (this.VerifyOwnership(UserId))
            {
                case UserStatus.Current:
                    UserId = this.CurrentUserIdentity.GetUserId();
                    break;
                case UserStatus.Stranger:
                    ViewBag.Username = this.Db.Profiles.Where(profile => profile.UserId == UserId).FirstOrDefault().Name;
                    break;
                case UserStatus.Undefined:
                    return new HttpNotFoundResult("Invalid User.");
            }

            return View("Index", this.GetUserReviews(UserId));
        }

        [ProfileVerification]
        public ActionResult Create(int contractId)
        {
            RentContract contract = this.Db.Contracts.Find(contractId);

            if (contract == null)
            {
                return new HttpNotFoundResult($"There is no contract with id {contractId}.");
            }

            RentReview review = new RentReview { Contract = contract };

            return View(review);
        }

        [HttpPost]
        [ProfileVerification]
        public ActionResult Create(RentReview review, int contractId)
        {
            try
            {
                if (ModelState.IsValid && review != null)
                {
                    review.WrittenBy = this.GetCurrentUserProfile();
                    this.Db.Reviews.Add(review);
                    this.Db.SaveChanges();
                }

                RentContract contract = this.Db.Contracts.Find(contractId);

                if (contract != null)
                {
                    review.Contract = contract;

                    if (review.WrittenBy.UserId == contract.Customer.UserId)
                    {
                        contract.CustomerReview = review;
                    }

                    if (review.WrittenBy.UserId == contract.Item.Owner.UserId)
                    {
                        contract.OwnerReview = review;
                    }

                    this.Db.Entry(contract).State = EntityState.Modified;
                    this.Db.SaveChanges();
                }

                return RedirectToAction("Index", "Contract", null);
            }
            catch
            {
                return View();
            }
        }

        public ActionResult GetSummary(string UserId)
        {
            if (string.IsNullOrEmpty(UserId))
            {
                return new HttpUnauthorizedResult("No user ID was is associated with this request.");
            }

            return PartialView("ReviewSummary", this.GetUserReviews(UserId));
        }

        public ActionResult GetItemReviewSummary(int itemId)
        {
            return PartialView("ReviewSummary", this.GetItemReviews(itemId));
        }

        public ActionResult IndexForItemReviews(int itemId)
        {
            ViewBag.IsItem = true;
            ViewBag.Item = this.Db.Inventory.Find(itemId).Name;
            return View("Index", this.GetItemReviews(itemId));
        }

        [NonAction]
        public IEnumerable<RentReview> GetUserReviews(string UserId)
        {
            if (string.IsNullOrEmpty(UserId))
            {
                return null;
            }

            IEnumerable<RentContract> associatedContracts = this.Db.Contracts.Where(contract => contract.Item.Owner.UserId == UserId ||
                                                                                                contract.Customer.UserId == UserId).ToList();

            List<RentReview> incomingReviews = associatedContracts.Where(contract => contract.Customer.UserId == UserId &&
                                                                                            contract.OwnerReview != null &&
                                                                                            contract.CustomerReview != null)
                                                                        .Select(contract => contract.OwnerReview).ToList();

            incomingReviews.AddRange(associatedContracts.Where(contract => contract.Item.Owner.UserId == UserId &&
                                                                                    contract.CustomerReview != null &&
                                                                                    contract.OwnerReview != null)
                                                                .Select(contract => contract.CustomerReview));

            return incomingReviews;
        }

        public IEnumerable<RentReview> GetItemReviews(int itemId)
        {
            IEnumerable<RentReview> itemReviews = this.Db.Contracts.Where(contract => contract.Item.Id == itemId &&
                                                                                    contract.OwnerReview != null &&
                                                                                    contract.CustomerReview != null).
                                                                                    Select(contract => contract.CustomerReview)
                                                                                    .ToList();

            return itemReviews;
        }
    }
}

RentReview/RentReview/Views/Shared/GlobalSummary.cshtml
@model string

<div class="row row-eq-height">
    <div class="col-sm-12 col-md-6 col-lg-3 mb-3 p-2">
        <div class="card border-primary h-100">
            <div class="card-body">
                <h5 class="card-title"><i class="fa fa-truck"></i> Inventory</h5>
                <p class="card-text">@Html.Action("GetItemCount", "Inventory", new { UserId = Model })</p>
            </div>
            <div class="card-footer">
                <a class="float-right" href="@Url.Action("Index", "Inventory", new { UserId = Model })">Go to inventory <i class="fa fa-chevron-right"></i></a>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-6 col-lg-3 mb-3 p-2">
        <div class="card border-primary h-100">
            <div class="card-body">
                <h5 class="card-title"><i class="fa fa-handshake-o"></i> Contracts</h5>
                <p class="card-text" id="ContractsSummary">@Html.Action("GetContractCount", "Contract", new { UserId = Model })</p>
            </div>
            <div class="card-footer">
                <a class="float-right" href="@Url.Action("Index", "Contract", new { UserId = Model })">Go to Contracts <i class="fa fa-chevron-right"></i></a>
            </div>
        </div>
    </div>
    <div class="col-sm-12 col-md-12 col-lg-6 mb-3 p-2">
        <div class="card border-primary h-100">
            <div class="card-body">
                <h5 class="card-title"><i class="fa fa-star-o"></i> Reviews</h5>
                <p class="card-text" id="ReviewsSummary">
                    @Html.Action("GetSummary", "Review", new { UserId = Model })
                </p>
            </div>
            <div class="card-footer">
                <a class="float-right" href="@Url.Action("Index", "Review", new { UserId = Model })">Go to Reviews <i class="fa fa-chevron-right"></i></a>
            </div>
        </div>
    </div>
</div>

RentReview/RentReview/Views/Shared/Item.cshtml
@model RentReview.Models.RentItem

<div class="card-header text-right shadow p-2">
    @Html.ActionLink("Rent", "Rent", "Contract", new { itemId = Model.Id }, null)
</div>

<div class="card-body text-dark">
    <h3>@(Model.Name)</h3>
    <p>
        @(Model.City), @(Model.Country)<br />
        Category: @(Model.Category)
    </p>

    <div class="collapse" id="details@(Model.Id)">
        <div class="card card-body">
            @{ if (!string.IsNullOrEmpty(@Model.Url))
                {
                    <a href="@Model.Url"><i class="fa fa-external-link"></i> External Reference</a>
                }
            }
            <p>
                <b>Description:</b><br />
                @(Model.Description)
            </p>

            <p>
                <b>Review Summary: </b>
                <a href="@Url.Action("IndexForItemReviews" , "Review", new { itemId = Model.Id })">
                    <i class="fa fa-external-link"></i>
                </a>
            </p>
            @Html.Action("GetItemReviewSummary", "Review", new { itemId = Model.Id })
        </div>
    </div>
</div>

RentReview/RentReview/Views/Shared/Logo.cshtml
<svg id="Layer_1" class="logo" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 232.7 233.4"><title>RRFinalLogo</title><path d="M306.48,279.63h91.91c11.31,0,20.72,7,23.56,17.7a25.5,25.5,0,0,1,.86,6.5q0,92.46,0,184.91a23.81,23.81,0,0,1-18.92,23.67,25.1,25.1,0,0,1-5.47.58q-91.9,0-183.82,0a23.86,23.86,0,0,1-23.77-18.81,25.27,25.27,0,0,1-.61-5.34q-.06-92.56-.07-185.15a23.93,23.93,0,0,1,24.33-24.08Q260.46,279.61,306.48,279.63Zm-92.87,73.95h1.49c6.68,0,13.35-.06,20,0,5.32.06,10.64.11,15.94.47a14.14,14.14,0,0,1,12.8,10.46,21.47,21.47,0,0,1,.33,8.45,13.84,13.84,0,0,1-11.36,11.91,73.21,73.21,0,0,1-10,.94c-9.32.19-18.64.2-28,.27h-1.26v21c3.18,0,6.29,0,9.4,0a20,20,0,0,1,16.45,8.15c2.86,3.76,5.69,7.54,8.34,11.44,7.4,10.91,14.71,21.89,22.05,32.85a1.93,1.93,0,0,0,1.76,1.13c9.72-.05,19.44,0,29.16,0,.32,0,.65-.07,1.16-.12-.93-1.49-1.75-2.81-2.58-4.12C292.25,445.25,285.19,434.06,278,423a57.5,57.5,0,0,0-19.7-18.78A1.68,1.68,0,0,1,258,404c3.49-.95,7.09-1.71,10.55-2.91,10-3.5,17.33-10,20.78-20.23a38.89,38.89,0,0,0-.4-26.9c-4.12-10.86-11.78-17.85-23.31-20.3a101.69,101.69,0,0,0-20.14-1.94c-10.27-.09-20.55,0-30.83,0-.35,0-.69.05-1.08.08ZM354.27,403.9c3.26-.89,6.87-1.66,10.32-2.85,9.07-3.14,16-8.82,19.82-17.78a38.59,38.59,0,0,0,.68-29c-4-10.89-11.55-18-23.09-20.55a100,100,0,0,0-20.48-2c-10.28-.1-20.56,0-30.84,0-.34,0-.69.05-1.06.08v21.86h1.48c6.64,0,13.28-.06,19.92,0,5.31,0,10.64.12,15.94.46a14.16,14.16,0,0,1,12.91,10.48,21.47,21.47,0,0,1,.33,8.45,13.84,13.84,0,0,1-11.37,11.9,73.06,73.06,0,0,1-10,.94c-9.31.19-18.63.2-27.95.27h-1.25v20.77c.47,0,.86,0,1.25,0,3.51.14,7,.22,10.54.46a16.43,16.43,0,0,1,11.07,4.82,66.93,66.93,0,0,1,7,8.46c8.86,12.92,17.58,25.94,26.33,38.93a2.16,2.16,0,0,0,2,1.12c9.56-.05,19.11,0,28.67,0h1.31a7.78,7.78,0,0,0-.39-.89C390.22,448.3,383,436.8,375.7,425.42c-3.51-5.45-7.33-10.71-12.44-14.83C360.29,408.19,357.13,406,354.27,403.9Z" transform="translate(-190.12 -279.63)" /></svg>

RentReview/RentReview/Views/Shared/MiniReview.cshtml
@model int

@if (Model <= 5 && Model >= 0)
{
    <span class="text-warning tshadow">
        @for (int index = 0; index < Model; index++)
        {
            <i class="fa fa-star"></i>
        }

        @for (int index = 0; index < 5 - Model; index++)
        {
            <i class="fa fa-star-o"></i>
        }
    </span>
}

RentReview/RentReview/Views/Shared/Profile.cshtml
@model RentReview.Models.UserProfile
@using Microsoft.AspNet.Identity;
@{
    string displayName = Request.IsAuthenticated && User.Identity.GetUserId().Equals(Model.UserId) ? "(Me)" : string.Empty;
}

<div>
    <div id="@Model.UserId" class="row align-content-end shadow border-bottom border-dark p-1 m-2 w-auto text-center profile-thumbnail">
        <div class="col-auto w-auto p-0 text-right">
            @if (string.IsNullOrEmpty(Model.Image))
            {
                <i class="fa fa-user-circle-o picture m-2 rounded-circle"></i>
            }
            else
            {
                @:<img src=@($@"/images/ProfilePictures/{Model.Image}") class="picture m-2 rounded-circle" alt="N/A">
            }
        </div>
        <div class="col w-100 align-bottom h-auto p-1 text-left details">
            <p class="m-0">
                <a href="@Url.Action("Index","Profile", new { UserId = Model.UserId })" target="_blank">
                    <i class="fa fa-external-link"></i>
                </a>
                @Model.Name <b>@displayName</b>
                <br>
                <small>
                    @Model.Email<br>
                    @Model.MobileNumber
                </small>
            </p>
        </div>
    </div>
</div>

RentReview/RentReview/Views/Shared/Response.cshtml
@model RentReview.Models.UserResponseViewModel
@using Microsoft.AspNet.Identity;

<div>
    @switch (Model.Response)
    {
        case RentReview.Models.UserResponse.Approved:
            <p class="text-success small"><i class="fa fa-check-circle"></i> Approved</p>
            break;
        case RentReview.Models.UserResponse.Declined:
            <p class="text-danger small"><i class="fa fa-remove"></i> Declined</p>
            break;
        case RentReview.Models.UserResponse.WaitingReponse:
            if (Request.IsAuthenticated && User.Identity.GetUserId().Equals(Model.UserId))
            {
                <div class="row w-auto">
                    <div class="col w-auto">
                        @using (Html.BeginForm("Approve", "Contract", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.ContractId, new { Name = "Id" });
                            <button class="btn btn-link text-success p-0" type="submit">Approve</button>
                        }
                    </div>
                    <div class="col w-auto">
                        @using (Html.BeginForm("Decline", "Contract", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.ContractId, new { Name = "Id" });
                            <button class="btn btn-link text-danger p-0" type="submit">Decline</button>
                        }
                    </div>
                </div>
            }
            else
            {
                <p class="text-warning small"><i class="fa fa-clock-o"></i> Waiting approval</p>
            }
            break;
    }
</div>

RentReview/RentReview/Views/Shared/Review.cshtml
@model RentReview.Models.RentReview

<div class="card border-secondary h-100 shadow">
    <div class="card-header text-left">
        <h6><strong>Rating: @Model.Rating</strong> @Html.Partial("MiniReview", Model.Rating)</h6>
    </div>
    <div class="card-body text-secondary">
        <p class="text-success"><b>Pros</b></p>
        <ul class="text-success">
            @if (Model.Pros != null && Model.Pros.Count() > 0)
            {
                foreach (string pro in Model.Pros.Split('\n'))
                {
                    if (!string.IsNullOrWhiteSpace(pro))
                    {
                        <li>@pro</li>
                    }
                }
            }
            else
            {
                <li>None</li>
            }
        </ul>

        <p class="text-danger"><b>Cons</b></p>
        <ul class="text-danger">
            @if (Model.Cons != null && Model.Cons.Count() > 0)
            {
                foreach (string con in Model.Cons.Split('\n'))
                {
                    if (!string.IsNullOrWhiteSpace(con))
                    {
                        <li>@con</li>
                    }
                }
            }
            else
            {
                <li>None</li>
            }
        </ul>

        <p class="text-dark">
            <b>Comments</b><br />
            @Model.Comments
        </p>
    </div>
    <div class="card-footer h-auto m-0 py-0 px-2">
        <p class="text-secondary text-right"><small>@Model.WrittenBy.Name</small></p>
    </div>
</div>

RentReview/RentReview/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Rent Review</title>
    <link rel="manifest" href="App_Start/Google/manifest.json">
    <meta name="theme-color" content="#003366" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand text-info p-0 m-0 mr-5" href="@Url.Action("Index", "Home")">
            <span class="beta align-text-top p-0">
                @Html.Partial("Logo")
                <small class="align-text-top p-0 m-0" style="line-height: 1.0;">beta</small>
            </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Inventory")">Inventory</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Contract")">Contracts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Review")">Reviews</a>
                </li>
            </ul>

            @using (Html.BeginForm("Search", "Profile", FormMethod.Get, new { @class = "mr-3" }))
            {
                @Html.AntiForgeryToken()
                <div class="input-group">
                    <input type="text" class="form-control" name="searchTerm" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-outline-primary" type="submit"><i class="fa fa-search"></i></button>
                    </div>
                </div>
            }

            @Html.Partial("_loginPartial")

        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()

        <footer class="container">
            <p class="text-center">&copy; @DateTime.Now.Year - Rent Review</p>
            <p class="text-center">By using our site you acknowledge that you have read and understand our <a href="@Url.Action("PrivacyPolicy", "Home")">Privacy Policy</a>.</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/rentreview")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>